// Downloads open-source icon SVGs and prints C# path data for the shell.
//  - UI icons: Lucide (ISC licence)  https://lucide.dev
//  - brand marks: Simple Icons (CC0) https://simpleicons.org
const ui = {
  ArrowLeft: "arrow-left",
  ArrowRight: "arrow-right",
  Reload: "rotate-cw",
  Close: "x",
  Home: "house",
  Star: "star",
  Plus: "plus",
  Minus: "minus",
  Square: "square",
  Menu: "menu",
  Shield: "shield",
  Lock: "lock",
  Search: "search",
  Download: "download",
  Theme: "sun-moon",
  Sparkles: "sparkles",
  Check: "check",
  User: "user",
  Palette: "palette",
  Globe: "globe",
  External: "external-link",
  Copy: "copy",
  Retry: "refresh-cw",
  Offline: "cloud-off"
};

const brand = {
  BrandGoogle: "google",
  BrandDuckDuckGo: "duckduckgo",
  BrandBrave: "brave",
  BrandBing: "bing"
};

const num = (attrs, key, fallback = 0) => (attrs[key] !== undefined ? Number(attrs[key]) : fallback);

function attrsOf(tag) {
  const out = {};
  for (const [, k, v] of tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) out[k] = v;
  return out;
}

function toPath(element) {
  const name = element.match(/^<([a-zA-Z]+)/)[1].toLowerCase();
  const a = attrsOf(element);

  if (name === "path") return a.d;
  if (name === "line") return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
  if (name === "polyline" || name === "polygon") {
    const pts = a.points.trim().split(/[\s,]+/);
    let d = `M${pts[0]} ${pts[1]}`;
    for (let i = 2; i < pts.length; i += 2) d += `L${pts[i]} ${pts[i + 1]}`;
    return name === "polygon" ? `${d}Z` : d;
  }
  if (name === "circle" || name === "ellipse") {
    const cx = num(a, "cx"), cy = num(a, "cy");
    const rx = name === "circle" ? num(a, "r") : num(a, "rx");
    const ry = name === "circle" ? num(a, "r") : num(a, "ry");
    return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${rx * 2} 0a${rx} ${ry} 0 1 0 ${-rx * 2} 0`;
  }
  if (name === "rect") {
    const x = num(a, "x"), y = num(a, "y"), w = num(a, "width"), h = num(a, "height");
    const r = num(a, "rx", num(a, "ry", 0));
    return r > 0
      ? `M${x + r} ${y}h${w - r * 2}a${r} ${r} 0 0 1 ${r} ${r}v${h - r * 2}a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - r * 2)}a${r} ${r} 0 0 1 ${-r} ${-r}v${-(h - r * 2)}a${r} ${r} 0 0 1 ${r} ${-r}z`
      : `M${x} ${y}h${w}v${h}h${-w}z`;
  }
  return "";
}

async function fetchSvg(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  return response.text();
}

function pathsFrom(svg) {
  const body = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"));
  return [...body.matchAll(/<([a-zA-Z]+)([^>]*)\/?>/g)]
    .map((m) => toPath(m[0]))
    .filter(Boolean);
}

// Each SVG child is its own path starting at the origin. When they are flattened into a
// single string, a later "m dx dy" would be relative to the previous subpath, so it is
// rewritten as an absolute move followed by relative lines.
function rebase(d) {
  return d.replace(/^m\s*([-\d.]+)[\s,]+([-\d.]+)\s*/, "M$1 $2l");
}

function flatten(list) {
  return list.map((d, i) => (i === 0 ? d : rebase(d))).join(" ");
}

const lines = [];
for (const [name, slug] of Object.entries(ui)) {
  const svg = await fetchSvg(`https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/${slug}.svg`);
  const d = flatten(pathsFrom(svg)).replace(/\s+/g, " ");
  lines.push(`    /// <summary>${slug}</summary>\n    public const string ${name} = "${d}";`);
}

const brandLines = [];
for (const [name, slug] of Object.entries(brand)) {
  try {
    const svg = await fetchSvg(`https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/${slug}.svg`);
    const d = flatten(pathsFrom(svg)).replace(/\s+/g, " ");
    brandLines.push(`    /// <summary>${slug}</summary>\n    public const string ${name} = "${d}";`);
  } catch (error) {
    brandLines.push(`    /// <summary>${slug} (unavailable: ${error.message})</summary>\n    public const string ${name} = "";`);
  }
}

process.stdout.write(`// Generated by work/tools/IconFetch/IconFetch.js\n`);
process.stdout.write(`// UI icons: Lucide (ISC). Brand marks: Simple Icons (CC0). Both 24x24 viewBox.\n`);
process.stdout.write(`namespace Nibble.Controls;\n\npublic static class IconData\n{\n`);
process.stdout.write(`${lines.join("\n\n")}\n\n`);
process.stdout.write(`    // ---- search engine brand marks (filled, not stroked) ----\n\n`);
process.stdout.write(`${brandLines.join("\n\n")}\n}\n`);
